package co.com.ceiba.drools.maprulesdrools.object


import co.com.ceiba.drools.maprulesdrools.object.Dato
import co.com.ceiba.drools.maprulesdrools.object.Grupo
import co.com.ceiba.drools.maprulesdrools.object.Recomendacion
import java.util.List

declare Recomendacion
	@propertyReactive
end	

rule "grupo"
when
	$grupo : Grupo()
	$list : List() from collect (Dato(grupo == $grupo.getId()))
then
end

rule "ITU-001-1" extends "grupo"
	agenda-group "MAIN"
when
    Dato(codigoVar == "3071", sistemaVar == "concept", codigoVal in ('25'), sistemaVal == "concept", contexto contains "8368") &&
    Dato(codigoVar == "3072", sistemaVar == "concept", codigoVal in ('188'), sistemaVal == "concept", contexto contains "8368") from $list
then
	for( int i = 0; i < $list.size(); i++ ){
        Dato d = (Dato)$list.get(i);
        System.out.println("rule 1: "+d.getCodigoVar()+ ": "+d.getGrupo());
        }
    drools.setFocus("1");
end

rule "ITU-001-2"
	agenda-group "1"
when
    Dato(codigoVar == "3073", sistemaVar == "concept", codigoVal in ('184'), sistemaVal == "concept", contexto contains "8368")
    $r: Recomendacion($l: actions)
then
	String[] actions = {"alerta, Dormir 24 horas"};
	for( int i = 0; i < actions.length; ++i ){
    	String s = (String)actions[i];
    	$l.add(s);
  	}
end


