package co.com.ceiba.drools.maprulesdrools.object

import co.com.ceiba.drools.maprulesdrools.object.Dato
import co.com.ceiba.drools.maprulesdrools.object.Grupo
import java.util.List
import java.util.ArrayList

rule "ITU-001-1"
when
	$grupo : Grupo()
	$list : List() from accumulate( $datoObject: Dato(grupo == $grupo.getId());
				                   collectList($datoObject))
then
	System.out.println($list.get(0).getGrupo());
end


