package co.com.ceiba.drools.maprulesdrools.object
import co.com.ceiba.drools.maprulesdrools.object.Dato
import co.com.ceiba.drools.maprulesdrools.object.Grupo
import co.com.ceiba.drools.maprulesdrools.object.Recomendacion
import java.util.List
declare Recomendacion
	@propertyReactive
end	
rule "Validar grupo"
when
	$grupo : Grupo()
	$list : List() from collect (Dato(grupo == $grupo.getId()))
then
end

rule "Rule_ITU0001_0" extends "Validar grupo"
	agenda-group "MAIN"
    when
    	Dato(codigoVar == "3071", sistemaVar == "concept", codigoVal in ('25'), sistemaVal == "concept", contexto contains "8368") &&
    Dato(codigoVar == "3072", sistemaVar == "concept", codigoVal in ('188'), sistemaVal == "concept", contexto contains "8368") from $list
    then
       System.out.println("Rule_ITU0001_0");
       drools.setFocus("1");
end


rule "Rule_ITU0001_1"
	agenda-group "1"
    when
    	Dato(codigoVar == "3074", sistemaVar == "concept", codigoVal in ('184'), sistemaVal == "concept", contexto contains "8368")
    	$r: Recomendacion($l: actions)
    then
     String[] actions = {"alerta,Descarte: -I.T.S (Infección de transmisión sexual),Prostatitis, Anormalidades anatómicas TGU (tracto genitourinario).",
"recomendacion,Tomar abundante agua",
"signos_alarma,Sospeche ITU complicada, paciente masculino"};
	for( int i = 0; i < actions.length; ++i ){
    	String s = (String)actions[i];
    	$l.add(s);
  	}
end


