package co.com.ceiba.drools.maprulesdrools.object


import co.com.ceiba.drools.maprulesdrools.object.Dato
import co.com.ceiba.drools.maprulesdrools.object.Grupo
import co.com.ceiba.drools.maprulesdrools.object.Recomendation
import java.util.List

declare Recomendacion
	@propertyReactive
end	

rule "grupo 15"
when
	$grupo : Grupo()
	$list : List() from collect (Dato(grupo == $grupo.getId()))
then
end

rule "Enfermedad15-001-1" extends "grupo 15"
	agenda-group "MAIN"
when
    Dato(codigoVar == "3076", sistemaVar == "concept", codigoVal in ('25'), sistemaVal == "concept", contexto contains "8368") &&
    Dato(codigoVar == "3077", sistemaVar == "concept", codigoVal in ('188'), sistemaVal == "concept", contexto contains "8368") from $list
then
	for( int i = 0; i < $list.size(); i++ ){
        Dato d = (Dato)$list.get(i);
        System.out.println("rule 15: "+d.getCodigoVar()+ ": "+d.getGrupo());
        }
	drools.setFocus("Enfermedad15-001-2");
end

rule "Enfermedad15-001-2"
	agenda-group "Enfermedad15-001-2"
when
    Dato(codigoVar == "3074", sistemaVar == "concept", codigoVal in ('184'), sistemaVal == "concept", contexto contains "8368")
    $r: Recomendation($l: actions)
then
	System.out.println("rule 15");
	String[] actions = {"alerta, Enfermedad15"};
	for( int i = 0; i < actions.length; ++i ){
    	String s = (String)actions[i];
    	$l.add(s);
  	}
end