package co.com.ceiba.drools.maprulesdrools.object


import co.com.ceiba.drools.maprulesdrools.object.Dato
import co.com.ceiba.drools.maprulesdrools.object.Grupo
import co.com.ceiba.drools.maprulesdrools.object.Recomendation
import java.util.List

declare Recomendacion
	@propertyReactive
end	

rule "grupo 8"
when
	$grupo : Grupo()
	$list : List() from collect (Dato(grupo == $grupo.getId()))
then
end

rule "Enfermedad08-001-1" extends "grupo 8"
	agenda-group "MAIN"
when
    Dato(codigoVar == "49100", sistemaVar == "concept", codigoVal in ('3104'), sistemaVal == "concept", contexto contains "8190") &&
    Dato(codigoVar == "49101", sistemaVar == "concept", codigoVal in ('49103'), sistemaVal == "concept", contexto contains "49099") from $list
then
	for( int i = 0; i < $list.size(); i++ ){
        Dato d = (Dato)$list.get(i);
        System.out.println("rule 8: "+d.getCodigoVar()+ ": "+d.getGrupo());
        }
	drools.setFocus("Diabetes-001-2");
end

rule "Enfermedad08-001-2"
	agenda-group "Diabetes-001-2"
when
    Dato(codigoVar == "8116", sistemaVar == "concept", codigoVal in ('1'), sistemaVal == "TEXT", contexto contains "8116")
    $r: Recomendation($l: actions)
then
	System.out.println("rule 8");
	String[] actions = {"alerta, Enfermedad08"};
	for( int i = 0; i < actions.length; ++i ){
    	String s = (String)actions[i];
    	$l.add(s);
  	}
end