package co.com.ceiba.drools.maprulesdrools;

rule "Rule_ITU0001_1"
    when
    	$codeGrupo: Grupo()
        $parametro: Parametro(codeGrupo == $codeGrupo, [codigo_variable == '2030' && sistema_variable == 'Concepto' && dato_valor == '2045' && sistema_valor == 'CIE10', codigo_variable == '2030' && sistema_variable == 'Concepto' && dato_valor == '2045' && sistema_valor == 'CIE10'])
    then
       	$parametro.setAcciones(ITU0001)
end

rule "Rule_ITU0001_0"
    when
    	$codeGrupo: Grupo()
        $parametro: Parametro(codeGrupo == $codeGrupo, [codigo_variable == '2030' && sistema_variable == 'Concepto' && dato_valor == 'N300, N301, N302, N303, N304, N308, N309, N390, N398, N399, O230, O231,O232, O232, O234, O239, R300, R301' && sistema_valor == 'CIE10', codigo_variable == '2030' && sistema_variable == 'Concepto' && dato_valor == '2045' && sistema_valor == 'CIE10'])
    then
       	$parametro.setAcciones(ITU0001)
end

rule "Rule_ITU0001_2"
    when
        $parametro: Parametro([codigo_variable == '2030' && sistema_variable == 'Concepto' && dato_valor == '2045' && sistema_valor == 'CIE10'])
    then
       	$parametro.setAcciones(ITU0001)
end

rule "Rule_ITU0001_3"
    when
        $parametro: Parametro([codigo_variable == '2030' && sistema_variable == 'Concepto' && dato_valor == '2045' && sistema_valor == 'CIE10'])
    then
       	$parametro.setAcciones(ITU0001)
end


